name: Test

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: [ '8.1', '8.2', '8.3', '8.4' ]
        symfony: [ '6.*', '7.*' ]
        dep: [highest,lowest]
        exclude: 
          - php: '8.1'
            symfony: '7.*'

    runs-on: ${{ matrix.operating-system }}

    name: Symfony ${{ matrix.symfony }}, ${{ matrix.dep }} deps, PHP ${{ matrix.php }}, ${{ matrix.operating-system }}

    steps:
    - uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: intl
        tools: flex

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      uses: ramsey/composer-install@v3
      with:
        dependency-versions: ${{ matrix.dep }}
        composer-options: --prefer-dist --no-progress --ignore-platform-reqs
      env:
        SYMFONY_REQUIRE: ${{ matrix.symfony }}

    - name: Run psalm
      run: vendor/bin/psalm
      if: matrix.dep == 'highest'

    - name: Run phpstan
      run: vendor/bin/phpstan analyse

    - name: Lint container
      run: tests/bin/console lint:container

    - name: Validate monorepo
      run: vendor/bin/monorepo-builder validate

    - name: Run phpunit
      run: |
        export SYMFONY_DEPRECATIONS_HELPER='max[direct]=0'
        vendor/bin/phpunit